---
resources:
    availability_zones: 3
    max_count: 768
    public_ip: True
    memory: 16GB
    cpus: 4
    gpu: false
    disks:
        - size: 8GB
          type: standard
          device_name: /dev/sda1

image:
    name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"

initialization:
    - path: "startup-scripts/cloud-config.yml"
